drachenwald/drachenwald

- peers/chivalry/index.md
- peers/laurel/index.md
Made a grammatical change are -> is
> Lia messes about

- activities/archery.md
- royals/index.html
commented out heirs link on royals index page
> Maria harsick

- _includes/chartered.html
fixed chartered group contact details
> chartered groups contact details fixed

- chartergroups/herbalist-guild/index.md
> Herbalist guild

- offices/webminister/index.md
"Raise issue" link in main text updated
> Web minister page

- _data/navigation.yml
- royals/drachenwald-succession.md
- royals/index.html
succession, royalty index, and navigation
> Updates to Royalty

- royals/index.html
> update chamberlain details

- offices/herald/book-of-ceremonies.md
This PR changes a letter, and probably clarifies.  
I heard this story at court. Glad to relive the moment by reading it again.
> Fix a typo in story of Albion

- offices/chatelaine/handouts.md
Perhaps reform the sentence to avoid the numeric part to refer to "present-day language"?
> Handouts: refer to our century as the 21st

- _data/thisisdrachenwald_feedlist.json
The file looks a little hand-edited.
This change was made my passing it into a JSON formatter.
In addition, a change in the titles of Silk & Quill's feeds made them unique.
> Format JSON for humans in thisisdrachenwald_feedlist.json

- royals/territorial-royals.md
This PR polishes some of the URLs, and removes some extra spaces.
> Territorial royals: Use https and update some URLs

- offices/webminister/index.md
This PR just formats a link using Markdown.
> webminister page: Use Markdown for link

- Gemfile
https://github.com/jekyll/jekyll/releases/tag/v4.3.2 https://my.diffend.io/gems/jekyll/4.3.1/4.3.2
> Update jekyll 4.3.1 to 4.3.2

- _layouts/single.html
As seen in examples on https://schema.org/CreativeWork.
> Use https: protocol for schema.org itemtype

- thisis/index.html
This PR fixes the link to "I want to add _my feed_ to This is Drachenwald".
> This is Drachenwald: link to GitHub Issues, add a paragraph break

- _posts/2024-03-12-Greetings-from-Posthorn.md
- _posts/2024-03-13-Crown-List.md
- groups/index.html
textual updates and one class name correction
> Text updates

- offices/webminister/webhistory.md
This PR updates and prettifies some of the Web Minister history content.
> Webminister history: copy-edits, linking, markup

- Gemfile
This will help in getting onto a regular release.
> Gemfile: add contextual comment on jekyll prerelease

- offices/webminister/webhistory.md
This PR does copy-editing of a page which I don't think is currently linked.
After we do some of this polish, it can soon be linked.
> Webhistory: rename page, bullet all sections, add preamble

- _includes/officer-contacts.html
This helps the Chatelaine page look good.
Fixes #151
> Fix: Render only HTML in .html file

- _includes/covid-notice.html
- assets/css/main.scss
- index.html
This PR extracts some loose style attributes into a named CSS class.
> Extract CSS class and use it

- peers/pelican/index.md
The previous link is old.
I will email someone who can make a decision about the Seneschal content, but I begin with this Pull Request. Update: I contacted the Pelican secretary.
> Pelican page: update link to Kingdom Law

- royals/heirs.html
The previous version seems invalid. This is valid, but, also, empty of content. Perhaps it could be omitted - I will keep it like this, for now.
> heirs.html: Indent YAML frontmatter

- offices/seneschal/law-council.md
Updates to Law Council page, as requested
> Updates to Law Council page

- groups/index.html
As per email from Tyndall, updated the contact information for France and added the fb group link.
> Updated contact information for France

- _posts/2025-03-02-LoI.md
> Letters of Intent to news items

- offices/herald/sendacourtreport.md
- signet as mailto instead of link
- include landed nobility in royals list
> Send a court report updates

- royals/heirs.html
The information sheet was missing some details. This pr adds the missing info.
> Added missing interests

- offices/archery-thrown-marshal/archery-rounds.md
The Captain General of Archers requested these changes by email. I don't yet have the confirmation whether the document that will be used is the same one that it currently links to, so if it changes, I'll update that separately.
> Changed text as requested by Captain General of Archers

- offices/seneschal/law-council.md
Her Majesty requested these changes by email. I'll ask about the law document, as the first page is rather large, so it might change later. Let's use this one to start with, though.
> Updated law document and updated and moved the new law to past proposals

- offices/archery-thrown-marshal/index.md
Removed extra reporting links, and updated the target archery handbook pdf.
Ref: email discussion with the current Captain General of Archers.
> Changes requested by Captain General of Archers, part 1

- offices/seneschal/index.md
- offices/webminister/index.md
- Changed Corpora link to the one that's updated automatically (new Corpora was just published, and the old link was hardcoded to the old file)
- Updated webminister name on the main page
> Misc improvements 8 2025
