README.md

This changes links, and in some cases, GitHub language, and some references to its UI.
- Pull Request
- Code button (to get the git:// URI)
- Paths referring to the gitlab setup
<details>
I don't know more about any Staging environment et cetera. So, I didn't go further than this change.
One JS include in `index.md`:
```html
<div  id="calendar"
legend="true"
links="local"
bidlinks="true"
></div>
<script type="text/javascript" src="https://sca-drachenwald.gitlab.io/events-calendar/calendar.js"></script>
```
</details>

README: Refer to GitHub

---

index.html

The URL http://lists.drachenwald.sca.org/mailman/listinfo/announcements points to a page with the text "This page no longer exists."
Other references not touched:
- There was an introductory reference to the Announcement list in a post from 2020, perhaps?
I saw this URL by searching for `http:` while trying to find outdated non-HTTPS links.

Remove reference to the defunct Announcement mailman list

---

_config.yml

This makes it easier to read relevant output from the startup of the container.

Configure SASS deprecation warnings not to show

---

.github/dependabot.yml

This adds an automatic update-by-PR GitHub feature, so that GitHub Actions versions for things like `actions/checkout@v3` are kept up to date automatically.

Configure a dependabot.yml to update the GitHub Actions, weekly

---

Dockerfile

This is the latest released version, a new version Ruby 3.3 is coming this December.
You can see the version string like:
docker exec -ti drachenwald-jekyll-1 ruby --version
Application started up fine.
---
I also looked online to see if people had had any snags upgrading, and someone documented their steps to get there, and how there _was_ an incompatibility, now fixed: https://www.miskatonic.org/2023/01/02/ruby-jekyll/

Upgrade Ruby version to 3.2

---

Gemfile

This PR adds the recommended gem [faraday-retry](https://github.com/lostisland/faraday-retry). This gets rid of a Ruby warning at startup.

Gemfile: add faraday-retry, per recommendation

---

.gitattributes

This PR changes the .gitattributes file to make it less intrusive, it no longer wishes to edit PDFs and other binary files.
I listed file types until the Git checkout began not to edit the PDFs.
Learn more about Git Attributes file:
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Git Attributes file to respect binary files

---

README.md

This helps the reader a little bit, since the long option --system tells RubyGems to update itself, "the RubyGems system".

README: Fix wording around rubygems update

---

events/pastevents.md

This fixes a small part of the issues noted in #110 - the display of an HTML comment as content.

Past events: avoid showing HTML comment as content

---

_layouts/autopage_artsci_tags.html
_layouts/autopage_cat.html
_layouts/autopage_tags.html
posts-index.html

This PR adds a slash to the end of each Tag link.
This is to try to make the site navigable from the Tag links in Posts.

Each link to a Tag ends with a slash

---

Dockerfile
Gemfile
docker-compose.yml

This PR makes `bundle exec jekyll serve` work
- use the not-yet-released version of Jekyll - see its https://github.com/jekyll/jekyll/blob/master/History.markdown for more details ("Add support for upcoming logger 1.4.3 ([#9392](https://github.com/jekyll/jekyll/pull/9392))")
- supply a needed gem which was standard library...but is now demoted to not-always-included.
This stops warnings like
> [...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/safe_yaml-1.0.5/lib/safe_yaml/transform.rb:1: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of safe_yaml-1.0.5 to add base64 into its gemspec.
From happening at start of the app.

Gemfile: add a gem which used to be standard library; use unreleased Jekyll which works

---

peers/laurel/laurel-faq.md

The keys to that data had changed. I used the same settings as used on the index.md in the same directory.
In addition: I checked all inclusions of this template, and now they all do it right.
Fixes: https://github.com/drachenwald/drachenwald/issues/117
Fragment of the same shown:

Laurel FAQ page: include Secretary email correctly

---

offices/chronicler/kingdom-newsletter.md

This changes a text that mentioned outdated things about having to log on to a website to download Dragon's Tale. This change simplifies the wording and updates the link. The previous wording had to talk about membership, which is no longer required.
The same link is used at the start of the page. (I guess it's good to be redundant, and have it discoverable in more places.)
See #118
In order not to go and update others' content, I emailed Chronicler about this.

Kingdom Newsletter: clarify link text to get digital D.T.

---

offices/webminister/index.md
offices/webminister/tools.md

This PR fixes #121
It adds a new article, "Tools", which has the local group webminister as its audience.
I used the "custom frontmatter" and a Liquid function to list the users of the different technologies in a easy-to-overview way.
Screenshot:

Webminister Tools page: summarize what Kingdom offers webministers

---

events/pastevents.md

This PR changes the Past events page to **filter out too-new events**.
This makes this page more tolerant of wrong data given to it.
A JS script on the page, which knows the current date could hide not-yet-past rows!
Fixes #58

Past events listing: Avoid presenting not-past events

---

offices/archery-thrown-marshal/index.md
offices/chatelaine/index.md

As yahoo groups no longer exist - all references to them have now been removed from the site.

removal of references to yahoo groups

---

peers/laurel/laurel-roster.md

The JSON contained data with `-` in the name, not `_`.
This fixes #147
~~The long fix would be to normalize these two kind of data at the point of collection, making them the empty string, as the template expected.~~

Laurel roster: fix blank bullet point for "other online presence"

---

events/pastevents.md

The quotes around the data- attribute were essential.
Before this change:

Past events: avoid outputting HTML

---

_includes/footer.html
_includes/footer/custom.html

This PR changes the footer where the links to "Edit this page on GitHub" are placed. With that, the issue that "the same path and URL are offered in the links" is fixed.
This PR moves those links to a "dynamic footer", which is rendered _before_ the cached footer. That's a part of Jekyll theme we are using.
A small side-effect, which I think we should accept, is that the custom, dynamic content is rendered before the fixed one.
The cached footer would always have the same page.path, page.url parameters. The "footer/custom.html" allows customization, with dynamic data.
<details>
The inclusion in the theme:
https://github.com/mmistakes/minimal-mistakes/blob/93022d6432f277eb5d83677fa50e4120f1281b04/_layouts/default.html#L29
</details>
Fixes #71

Move Edit on GitHub links to non-cached footer

---

assets/css/main.scss

This PR adds a new CSS class to slightly simplify layout work in the content pages.
We have in place a 800px and centered CSS class. But: There are pages which also manual styling to get "600px centered".
This change extracts the centeredness via auto margins to a CSS class for utility usage, and defines a 600px wide class, too.
I used https://sass-lang.com/playground/#eJwzNNTLTSxKz8zTzUlNK9FNzEvRLcpMzwCySkvyFaq5FBSQpK0UQKLWCEGwUphoLReXXnJqXklqUWoK2KDcxApdCwMDsCkOqRUlqXkpCnhsg5hboVuemVKSYaUA1FlQgcNUM7JNNYOZCgBNNFFj to play with the SCSS.

main.scss: add a centered-and-max-600 CSS class

---

Gemfile

Now that the issues that we waited for being released have been released, we can go back to using a RubyGems.org-served regular version, instead of a GitHub.com git-served version.

Gemfile: refer always to Jekyll on a released version

---

offices/herald/sendacourtreport.md

Changes based on https://github.com/drachenwald/drachenwald/issues/182 for
> the link "Court Reporting overview" (second bullet under the heading Court Reporting) goes to:
https://drachenwald.sca.org/offices/herald/sendacourtreport/ ... which has several errors:
-> The link to "royal family of DW" (under the heading Send a court report) only links to TRM & TRH, which is inconsistent with the following text:
-> "the royals who you were serving: Crown, Coronet, or your baron and baroness" (first bulletpoint under the heading "Who to contact")
-> Change the link in the fourth bulletpoint to "mailto:[signet@drachenwald.sca.org](mailto:signet@drachenwald.sca.org)"
- signet as mailto instead of link
- include landed nobility in royals list

Updates to send a court report page

---

offices/herald/drachenwaldawardsorders.md

Fixed Orders of Merit heading level, as it was showing as a heading at the same level as the lower ones. See https://github.com/drachenwald/drachenwald/issues/211

Fixed Orders of Merit heading level
